### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by DanielHudson** [videojs/videojs-youtube#67] opened 2014-02-09 00:42 UTC
```
Failed to execute 'postMessage' on 'DOMWindow': 
The target origin provided ('http://www.youtube.com') does not match
the recipient window's origin ('https://www.youtube.com').
```

When logged into youtube the protocol is usually automatically redirected to HTTPS. This causes the above error when embedding a videojs-youtube video on an HTTP site.

**Comment by wegorich** [comment] 2016-04-07 21:15
The issue is still there... It happend magically have two project, same code base, one with this issue. Other not :( 

www-widgetapi.js:98 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.youtube.com') does not match the recipient window's origin ('https://www.youtube.com').

 Is there an upproach to avoid it?

**Comment by pietrovismara** [comment] 2016-06-07 14:40
+1

**Comment by CavalcanteLeo** [comment] 2016-09-03 06:17
+1

**Comment by NathanSweet** [comment] 2016-09-07 09:32
This is not fixed and still occurring.

**Comment by mpetkov** [comment] 2016-09-27 09:16
Anyone know of when this will be fixed?

**Comment by sanketj14** [comment] 2016-09-27 15:51
it's replicable on chrome as well at my end. if anyone could please provide the description to why this is happening, I don't think this is related to SSL.

**Comment by claudio-incomedia** [comment] 2016-10-05 09:56
I'm facing the very same issue. It seems that this bug just came back after an update oj videojs-youtube.

**Comment by gouravmakhija18** [comment] 2016-10-13 08:08
I am also facing same issue 

> www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://sitename.com').

e.g. http://jsfiddle.net/5gcgu/1/

**Comment by kleninb** [comment] 2016-12-08 06:32
Same here 

> yt_api.js:95 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://youtube.com') does not match the recipient window's origin ('https://www.youtube.com').

**Comment by kleninb** [comment] 2016-12-08 06:39
My problem with youtube video is, when I play one video close it before I open another video,
both of them are playing one in the background and one live.
But In localhost (system) it is working fine.

**Comment by kellsbells** [comment] 2017-01-24 22:21
+1

**Comment by edernucci** [comment] 2017-02-15 12:17
+1

**Comment by hrehman200** [comment] 2017-04-06 07:25
+1

**Comment by gkatsev** [comment] 2017-04-06 14:55
Please, just posting `+1` is not helpful. I am unable to reproduce it locally and the only example that's posted is using just the youtube API and not videojs-youtube. Any guidance that can be provided for reproducing it (or even just solving it) would be good. Preferably, with a reduced test case.

Thanks.

**Comment by iCoderXXI** [comment] 2017-04-26 20:18
Hi all! I've got the same issue here https://developers.facebook.com/graph-academy/marketing-api/1/ "Login with Facebook" button is not working, getting several messages like "login-ads.php:50 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://developers.intern.facebook.com') does not match the recipient window's origin ('https://developers.facebook.com')" in console...

**Comment by manjudr** [comment] 2017-08-09 03:20
I am also facing same issue here
![image](https://user-images.githubusercontent.com/16288575/29103856-be2d8d00-7cdf-11e7-9b8d-d5c667204d3d.png)

**Comment by codechikbhoka** [comment] 2017-10-13 05:22
@manjudr were you able to solve it ? I am also facing the same problem

**Comment by manjudr** [comment] 2017-10-16 09:50
@codechikbhoka  Still that is not fixed yet somehow video is working but we were getting those errors in the console still.

**Comment by wuzinong** [comment] 2017-11-02 06:42
Does anyone can provide a way to catch this error ?

**Comment by AdamSalma** [comment] 2017-12-27 23:56
+1

**Comment by softdevstorm** [comment] 2018-01-18 19:08
I met same error.

Issue is like this "www-widgetapi.js:116 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://js.driftt.com')"

And javascript code is

<script>
                !function() {
                    var t;
                    if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0,
                            t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
                            t.factory = function(e) {
                                return function() {
                                    var n;
                                    return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
                                };
                            }, t.methods.forEach(function(e) {
                            t[e] = t.factory(e);
                        }), t.load = function(t) {
                            var e, n, o, i;
                            e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"),
                                o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js",
                                n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
                        });
                }();
                drift.SNIPPET_VERSION = '0.3.1';
                drift.load('pn4kvs3b3x4i');
            </script>

How can I solve this issue?

**Comment by codeofsumit** [comment] 2018-03-16 16:04
same here 🤔

**Comment by krishaamer** [comment] 2018-05-25 21:44
Still having this issue in 2018 ;/

**Comment by radiolondra** [comment] 2018-06-16 10:02
Confirmed. I have the same issue. So the issue is still there after years. Noone is able to fix this? :/

**Comment by Adetona** [comment] 2018-07-16 17:08
Having this issue as well.

**Comment by manjudr** [comment] 2018-07-16 17:11
Why this issue is closed ? Many of user are facing this issue still

**Comment by gkatsev** [comment] 2018-07-17 04:53
So, I finally took some time to investigate this and was able to reproduce after super carefully re-reading the original post, in my previous reading I didn't catch the nuance in the issue. However, a live test case would've helped this get reproduced a lot earlier, which is why it was still closed until now.

This was actually fixed in a really old version via the `forceSSL` option in #68 but during some refactor it was taken out. To solve this, we'd basically want to re-write the youtube url to always, or optionally, be https. Not having an option is probably best but I'm slightly worried that always using https could somehow cause issues somewhere. If anyone has thoughts, let me know. Or feel free to submit  PR to fix this :), happy to give pointers on it until I can fix it myself. Drop by on our [slack](http://slack.videojs.com).

**Comment by tjaneczko** [comment] 2018-07-18 14:30
@gkatsev I took a deeper look into this, it seems like it might be a timing issue with the YouTube IFrame API.  The IFrame API already loads everything over https, so implementing #68 again would offer no benefits, and actually loses us the benefit of having the IFrame API do all of the lifting for creating the iframe.  It looks like initially two messages are sent, the first one gets rejected due to the iframe not being initialized completely (it looks like): `{"event":"listening","id":1,"channel":"widget"}`.  They have a try / catch in the YouTube API, but according to the HTML5 spec for postMessage, browsers should silently fail postMessages where the origins don't match up, meaning the catch block is never hit.  Unfortunately, it looks like there's no suitable way for us to fix this without Google doing something on their end to fix the postMessage timing.

**Comment by tjaneczko** [comment] 2018-07-18 15:03
On the plus side it looks like this error only happens on the first event, and doesn't impact video playback at all, so it's unfortunately just a benign error message that pops up.

**Comment by gkatsev** [comment] 2018-07-19 21:29
Thanks for looking @tjaneczko. Seems like the issue currently isn't related to the original issue here. I think I got confused because I wasn't getting the error when the source was `https` but was getting it when it was `http` but the following day I was getting it for both sources. In addition, the new error isn't coming from us but from youtube's script. As @tjaneczko said, I don't notice this error impeding playback. I am also not seeing any errors logged in Firefox, probably because of the spec guidance of ignoring these types of errors. We potentially should open an issue against chrome so they won't show these errors.

**Closed by gkatsev** 2018-07-19 21:29 UTC

**Comment by harrybest** [comment] 2020-02-09 12:34
Wanted to share my experience here as it was resolved after few steps
1. convert the protocol of domain with https
2. and on youtube api function: onPlayerReady(event) add the mute function which is event.target.playVideo(); and it resolved the issue on mobile devices and also work each time.

Hope it help for you as well.

**Comment by yourchoice** [comment] 2020-03-19 15:51
I have similar problem problem with video.js@7.7.5 and youtube plugin v2.6.1

**Comment by yourchoice** [comment] 2020-03-19 16:31
FOr my case I think I resolved the problem with these options (i think i need just 'origin'):

{ ... , "youtube": { "iv_load_policy": 1, "origin": "{$SETTINGS.url}" } } 

I hope to help others to ...

**Comment by gilisegal** [comment] 2020-09-17 08:34
@yourchoice have you managed to solve this with video.js and youtube plugin?

**Comment by etomProductions** [comment] 2020-09-23 09:29
Hello,

Did anyone fix this issue please?

Thank you

**Comment by harrybest** [comment] 2020-09-23 09:36
> Hello,
> 
> Did anyone fix this issue please?
> 
> Thank you

This error occur due to different reasons means there are different solutions but here are two things you can try and hope it will fix the issue:
1. try using SSL 
2. Set the default load function to mute as some browser not supported autoplay video with voice so you have to make video muted by default.

**Comment by WartVader** [comment] 2022-10-03 11:56
I had that issue too. Fixed it simply adding `enablejsapi` (also set it first in `playerVars`) and `origin`
Changed it from this:
```
playerVars: {
    loop: 1,
    playlist: link,
    origin: window.location.origin
}
```
```
playerVars: {
    enablejsapi: 1,
    origin: window.location.origin,
    loop: 1,
    playlist: link
},
```
Seems like order is important, because it build query link by the order in `playerVars`

**Comment by mahekdobariya** [comment] 2023-03-23 06:24
> Why this issue is closed? Many of users are facing this issue still

**Comment by mahekdobariya** [comment] 2023-03-23 09:02
> same here
same here
