### ISSUE TITLE
Can't play on iOS

### ISSUE THREAD

**Issue by cpBurn** [videojs/videojs-youtube#357] opened 2016-01-25 16:23 UTC
I am not able to play it on iOS environment, and I am not sure if this is supported by this library.
Tested in iOS 8.3 (Iphone 6 Plus) and iOS 8.1.1 (iPad 4)
Works fine on Androids.

I attached the play method on click, and after I click, a loading spinner appears and after a while I got this message:
if playback doesn't begin shortly try restarting your device

I also got his warning:
WebGL: INVALID_ENUM: getParameter: invalid parameter name, WEBGL_debug_renderer_info not enabled

Any ideas?

**Comment by eXon** [comment] 2016-02-03 12:08
iOS is pretty darn a pain in the ass with playing a video with Javascript. Have you tried simple.html in the example folder? It works great for me.

**Comment by dnish** [comment] 2016-02-16 14:56
I'm having the same issue on Android and iOS, this is how I init my player:

    var video = videojs(elem).ready(function() {
                        this.play();
       });

It starts the loading spinner, but after a while I get the message "if playback doesn't begin shortly try restarting your device".

**Comment by kwims** [comment] 2016-02-27 23:30
I am having the exact same problem as @dnish . Works fine on safari desktop!

**Comment by dnish** [comment] 2016-02-27 23:33
@kwims I think that it is a problem with autoplay. If I remove autoplay and click manually on the play button, everything works fine. As far as I know, Android & iOS prevent autostart videos in Chrome and Safari by design.

**Comment by kwims** [comment] 2016-02-29 06:47
@dnish I tried to force the disable of autoplay but it is not changing anything.
Here is is my code. Anything you can spot ?
` this.player = videojs(player, {
              width: optionalWidth,
              height: optionalHeight,
              techOrder: ["youtube"],
              youtube: { "enablejsapi": 1, "autoplay" : 0 },
              src: ytSrcEl.src
            }, _.bind(function(){
              callback();
            },this));
....
 play: function () {
            this.player.play();
        },
`

**Comment by eXon** [comment] 2016-02-29 10:46
You cannot call play in javascript on mobile. It has to be done by the user.

You can look at [this example](https://github.com/eXon/videojs-youtube/blob/master/examples/simple.html) to learn how to use the tech correctly.

**Comment by kwims** [comment] 2016-02-29 13:32
Great. Thanks I will have a look.

**Comment by kwims** [comment] 2016-03-05 09:41
> You cannot call play in javascript on mobile. It has to be done by the user.
@eXon that was the issue. When the user press on the button it is all working good.

**Comment by gkatsev** [comment] 2016-05-10 19:44
Sounds like this can be closed?

**Comment by gkatsev** [comment] 2016-05-11 04:37
Closing, if it's still an option, let us know and we can re-open.

**Comment by cpBurn** [comment] 2016-05-11 09:21
Hey guys, sorry for being absent from this topic. 
In order to play the video in iOS, we can't bind any click event and trigger this

`this.player.play();`

Once I removed it, and let the iframe created by youtube handles the event, works fine. 
This is slightly different than a simple `<video>` tag where we can bind the click event and then trigger the play.

**Comment by gkatsev** [comment] 2016-05-11 15:29
Thanks @cpBurn, is this in the videojs-youtube tech code?
I guess I'll re-open this so we can investigate it fully.

**Comment by cpBurn** [comment] 2016-05-11 16:16
I am checking the videojs-youtube code and seems fine. On iOS is fairly easy to lose the click context and as Youtube api creates an iframe it gets even worse. I don't think this is videojs-youtube issue, I think we just can't handle the click manually on iOS, we can just rely on the iframe.

**Comment by dnish** [comment] 2016-05-11 16:19
Yep, we also using the plugin in production - manually adding an own click event or using autoplay isn't working on iOS. It isn't a plugin issue, it is prevented by iOS design.

**Comment by Abeansits** [comment] 2016-08-17 18:12
You will need to set the flag `mediaPlaybackRequiresUserAction` to `true` on the `UIWebView` or `WKWebView`.

**Closed** 2017-01-13 19:09 UTC
