### ISSUE TITLE
Video not playing in Internet Explorer

### ISSUE THREAD

**Issue by apkoudakos** [videojs/videojs-youtube#342] opened 2015-12-14 20:22 UTC
I'm using videojs-youtube 1.2.13 on Internet Explorer 11 (on a windows computer) and I get a black video, while the audio plays correctly. On all other browsers (both on windows and mac/iOS) it works fine and video is displaying correctly.

**Comment by eXon** [comment] 2015-12-14 23:27
Are you running a web server locally? What error do you have in the console?

**Comment by apkoudakos** [comment] 2015-12-15 06:57
Actually I'm not working locally, but I'm testing the website on my web server provider. Weirdly enough, there is no error in the console. The video is playing, but it's simply not showing and it's completely black (only on Internet Explorer). The audio on the other hand is playing perfectly. There is no problem at all instead with other browsers on all platforms and devices.

**Comment by apkoudakos** [comment] 2015-12-15 07:00
I wanted to add that I'm using videojs script version 4.12.5 and that tested and had the same problem (only on Internet Explorer) with videojs-youtube from version 1.2.6 all through version 1.2.13 which I'm currently using.

**Comment by grzegorzjudas** [comment] 2015-12-18 09:14
Did you try using videojs 5.3?

**Comment by apkoudakos** [comment] 2015-12-18 12:50
I just tried using videojs 5.3 and now videos don't play at all on any browser

**Comment by apkoudakos** [comment] 2016-01-17 09:02
Any help ?

**Comment by gkatsev** [comment] 2016-05-10 19:43
Looks like https://github.com/eXon/videojs-youtube/issues/376 is a duplicate of this issue.

**Comment by gkatsev** [comment] 2016-05-10 19:54
Using the latest version of videojs (5.9.2) and the latest code of videojs-youtube (what's in master) and it's working just fine for me on IE11.

**Comment by gkatsev** [comment] 2016-07-08 15:56
Closing this issue due to lack of activity. If it is still a problem and we get more information and a reduced test case, we will happily re-open the issue.

**Closed by gkatsev** 2016-07-08 15:56 UTC
